define(
   ({
       username: "Gebruikersnaam",
       password: "Wachtwoord",
       locale: "locale",
       units: "weergave-eenheid",
       unitsDefault: "Standaard eenheid uit de geslecteerde srs",
       unitsMeter: "Meter",
       unitsFeet: "Voet",
       srs: "Viewer SRS",
       agreement1: "Ik ga akkoord met de",
       agreement2: "Gebruiksvoorwaarden voor Street Smart.",
       headAgreement: "Gebruiksvoorwaarden",
       measure: "Metingen",
       toggleAll: "Alles Inschakelen / Uitschakelen",
       overlay: "Overlays",
       timetravel: 'Time Travel',
       streetName: 'Toon straatnaam',
       linkMapMove: 'Centreer cyclorama in kaart',
       saveMeasurements: 'Bewaar metingen',
       allowEditing: 'Attributen aanpassen',
       recordings: 'Opnames Toon schaal',
       display1: "1:1130 (standaard)",
       display2: "1:2258 (Ver)",
       display3: "1:4415 (Verder)",
       coverage: "Street Smart Dekkingslaag",

       navigation: "Navigatie",
       navigationButtons: 'Navigatie Knoppen',
       overlaysButton: 'Overlays Knop',
       elevationButton: 'Hoogteweergave Knop',
       reportblurringButton: 'Meld Blur fout Knop',
       measureButton: 'Meten Knop',
       saveimageButtonEnable: 'Beeld Opslaan Knop',
       imageinformationButton: 'Beeld Informatie Knop',
       zoominButton: 'Zoom-in Knop',
       zoomoutButton: 'Zoom-out Knop',

       typeSrs: "Typ of selecteer SRS",
       version: "Street Smart Widget voor Web AppBuilder @ versie 23.1.5",
   })
);
