define(
   ({
       username: "Benutzername",
       password: "Passwort",
       locale: "Sprache",
       units: "Anzeigeeinheiten",
       unitsDefault: "Standardeinheit von ausgewählten srs",
       unitsMeter: "Meter",
       unitsFeet: "Füße",
       srs: "Referenzsystem",
       agreement1: "Ich stimme den",
       agreement2: "Allgemeine Nutzungsbedingungen für Street Smart.",
       headAgreement: "Allgemeine Nutzungsbedingungen",
       measure: "Messungen",
       toggleAll: "Alle Aktivieren / Deaktivieren",
       overlay: "Überlagerungen",
       timetravel: 'Zeitreise',
       streetName: 'Straßenname',
       linkMapMove: 'Karte und Panorama binden',
       saveMeasurements: 'Messungen speichern',
       allowEditing: 'Attributbearbeitung',
       recordings: 'Anzeigeskala für Aufzeichnungen',
       display1: "1:1130 (Ursprünglich)",
       display2: "1:2258 (Weit)",
       display3: "1:4415 (Weiter)",

       navigation: "Navigation",
       navigationButtons: 'Navigations-Schaltflächen',
       overlaysButton: 'Überlagerungs-Schaltflächen',
       elevationButton: 'Elevation-Slider',
       reportblurringButton: 'Verpixelung melden',
       measureButton: 'Schaltflächen Messfunktionen',
       saveimageButtonEnable: 'Bild speichern Schaltflächen',
       imageinformationButton: 'Metadaten-Schaltfläche',
       zoominButton: 'Zoom-in Schaltfläche',
       zoomoutButton: 'Zoom-out Schaltfläche',

       typeSrs: "EPSG-Code eingeben oder Referenzsystem auswählen",
       version: "Street Smart Widget für Web AppBuilder @ Version 23.1.1",
   })
);
