define(
   ({
       username: "Nom d'utilisateur",
       password: "Mot de passe",
       locale: "Lieu",
       units: "Unités de mesure",
       unitsDefault: "Unité par défaut des srs sélectionnés",
       unitsMeter: "Mètres",
       unitsFeet: "Pieds",
       srs: "SRS",
       agreement1: "Je suis d'accord avec les",
       agreement2: "Termes et conditions de l'utilisateur pour Street Smart.",
       headAgreement: "Accord de l'utilisateur",
       measure: "Mesures",
       toggleAll: "Activer / Désactiver Tout",
       overlay: "Superpositions",
       timetravel: 'Historique',
       streetName: 'Visualiser les noms de rues',
       linkMapMove: 'Centrer la carte sur le cyclorama',
       saveMeasurements: 'Sauvegarder les mesures',
       allowEditing: 'Édition d\'attribut',
       recordings: 'Échelle d\'affichage des enregistrements',
       display1: "1:1130 (défaut)",
       display2: "1:2258 (Loin)",
       display3: "1:4415 (Plus loin)",

       navigation: "Navigation",
       navigationButtons: 'Boutons Navigation',
       overlaysButton: 'Bouton Superposition',
       elevationButton: 'Bouton Elevation',
       reportblurringButton: 'Bouton Reporter une erreur de floutage',
       measureButton: 'Bouton Mesures',
       saveimageButtonEnable: 'Bouton Sauvegarder une image',
       imageinformationButton: 'Bouton Information Image',
       zoominButton: 'Bouton Zoom-in',
       zoomoutButton: 'Bouton Zoom-out',

       typeSrs: "Tapez ou sélectionnez SRS",
       version: "Street Smart Widget pour Web AppBuilder @ version 23.1.1",
   })
);
